services:
  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: nyaruka
      POSTGRES_PASSWORD: nyaruka
      POSTGRES_DB: nyaruka
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
